# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            R Data
tagline:          'David Robinson and Neo Christopher Chung'
description:      'Data Analysis and Visualization Using R'
baseurl:          /RData

author:
  name:           'David Robinson'
  url:            http://dgrtwo.github.io/

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dgrtwo/RData